version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: musicDB
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    container_name: mysql

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/config
    ports:
      - "8000:8000"
    hostname: django
    container_name: django
    depends_on:
      - mysql  # MariaDB 컨테이너가 먼저 실행되도록 의존성을 설정합니다.
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
